name: reviewdog
on: pull_request
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node/npm
        uses: actions/setup-node@v1
        with:
          node-version: "15"

      - name: Run action-textlint
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "posts/**"
